apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-html-deploy
spec:
  selector:
    matchLabels:
      app: hello-html
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-html
    spec:
      containers:
      - name: hello-html
        image: gkpanshi/hello_html:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: hello-html
spec:
 selector:
   app: hello-html
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32082
 type: NodePort
