apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go-http-deployment
  labels:
    app: hello-go-http
spec:
  selector:
    matchLabels:
      app: hello-go-http
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-go-http
    spec:
      containers:
      - name: hello-go-http
        image: gkpanshi/hello_go_http:v0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"

---

apiVersion: v1
kind: Service
metadata:
  name: hello-go-http
spec:
  selector:
    app: hello-go-http
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
